### PR TITLE
Allow sexagesimal degree coordinates using different delimiters.

### LINKED ISSUE #4: Allow using sexagesimal notation for location
As of now location is specified as float numbers for latitude and longitude.

I propose using a notation to allow sexagesimal notation like the following:

```
[default]
latitude  = 52:08:16.5
longitude = 21:00:25.3
```

Any float on the degree or minute position will be properly converted and sum up to the inferior position, so this is equivalent to the previous one:

```
[default]
latitude  = 52:08.25:1.5
longitude = 21:00:25.3
```

8.25 minutes are 8 minutes and 15 seconds, so adding 1.5 seconds more it is 16.5 seconds.

### LINKED ISSUE #6: Bug at line 56
Line 56 is a not correct! 
len(elements) can be 1, and there would not be any elements[1]

### PR DESCRIPTION
**Pull request by miceno**
This PR allows providing location data in degree format using different delimiters.

Closes #4

### CODE REVIEW

**Comment by miceno** [comment]
Hi @rkaczorek 

Will you please advice if this PR makes sense?

Regards.

**Comment by miceno** [comment]
Hi again!

Does this PR make sense? @rkaczorek 

Thank you!

**Comment by miceno** [comment]
Hi again!

Will you please advice @rkaczorek ?

Thank you!

**Comment by rkaczorek** [comment]
@miceno thanks for your input. I missed this one but now its in the master

**Pull request merged**
